import type { Project, ProjectMedia } from "./types.ts";

const vis = "工作室視覺轉譯，不是產品截圖。";
const shotNote = "公開站實際畫面。狀態會隨部署變動。";

function cover(file: string, alt: string): ProjectMedia {
  return { src: `/media/covers/${file}`, alt, kind: "image", caption: vis };
}

function shot(file: string, alt: string): ProjectMedia {
  return { src: `/media/shots/${file}`, alt, kind: "image", caption: shotNote };
}

/** Zeabur-linked works beyond the eight featured case studies. */
export const linkedWorks: Project[] = [
  {
    slug: "tamkang-world",
    title: "淡江世界",
    subtitle: "五虎崗上的 3D 校園巡禮",
    category: "Spatial Design",
    year: "2026",
    status: "prototype",
    featured: false,
    summary: "在瀏覽器裡走一趟淡江。樸實剛毅的五虎崗做成可逛的 3D 校園，不是導覽 PDF，也不是 Google Earth 截圖。",
    problem: "新生與訪客對校園空間沒有身體感。需要一個立刻能開的 3D 巡禮，而不是先下載 App。",
    role: "空間體驗設計：場景節奏、校園識別與可立即操作的瀏覽器巡禮。",
    decisions: [
      "公開站標題就是「淡江世界」，一句話講完五虎崗。",
      "部署在 Zeabur 服務 forge-bloom-quiet-falcon。GitHub 目前為私有，公開操作走 Zeabur。",
    ],
    modalities: ["3D", "空間", "互動"],
    process: [
      "打開 forge-bloom-k7xq.zeabur.app",
      "點「開始巡禮」進入 3D",
      "WASD 移動、滑鼠轉視角，滾輪拉近",
      "開「校園圖鑑」對照建築",
    ],
    outputs: ["可逛的 3D 校園公開站"],
    stack: ["WebGL / 3D", "Zeabur"],
    limitations: [
      "GitHub forge-bloom-quiet-falcon 目前為私有，訪客打不開原始碼。",
      "效能依裝置而變，不宣稱完整數位雙生。",
    ],
    links: {
      github: "https://github.com/aa0968111723-prog/forge-bloom-quiet-falcon",
      live: "https://forge-bloom-k7xq.zeabur.app",
    },
    media: [
      cover("tamkang-world.jpg", "淡江世界光域靜物：晨光中的玻璃校園模型"),
      shot("tamkang-world.jpg", "淡江世界開場：開始巡禮、校園圖鑑、登入，背景是夕陽海岸"),
    ],
    sourceReferences: [
      {
        label: "公開站 · forge-bloom-k7xq.zeabur.app",
        href: "https://forge-bloom-k7xq.zeabur.app",
        note: "Zeabur 服務 forge-bloom-quiet-falcon。本次探測 RUNNING。og：五虎崗上的 3D 校園巡禮。",
      },
      {
        label: "GitHub · forge-bloom-quiet-falcon",
        href: "https://github.com/aa0968111723-prog/forge-bloom-quiet-falcon",
        note: "倉庫存在，目前為私有。公開操作請走 Zeabur。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "tamsui-drama",
    title: "淡江新生導覽",
    subtitle: "校園闖關 · 戲劇虛擬世界",
    category: "Real-world Experience",
    year: "2026",
    status: "prototype",
    featured: false,
    summary: "把淡江／淡水寫成可持續開發的劇本、場景與角色。公開站是柏能的校園闖關，不是 FrameLab。",
    problem: "迎新資料是 PDF 與路線圖，身體感不夠。需要一個能闖關、能走進場景的入口。",
    role: "敘事與互動設計：關卡節奏、角色與淡水場景。",
    decisions: [
      "獨立網域 tku-tamsui-drama-world-k4x9，不要跟 FrameLab 的 lunar-falcon 混用。",
      "開場是「安倢的校園闖關」，先玩再講系統。",
    ],
    modalities: ["互動", "敘事", "3D"],
    process: [
      "打開 tku-tamsui-drama-world-k4x9.zeabur.app",
      "等世界載入",
      "從第一集宮燈下的迎新開始",
      "依關卡走完校園",
    ],
    outputs: ["校園闖關公開站"],
    stack: ["Web", "Zeabur"],
    limitations: ["內容會隨學期更新，不宣稱完整學年劇本。"],
    links: {
      github: "https://github.com/aa0968111723-prog/tku-tamsui-drama-world",
      live: "https://tku-tamsui-drama-world-k4x9.zeabur.app",
    },
    media: [
      cover("tamsui-drama.jpg", "淡江新生導覽光域靜物：宮燈、闖關地圖與玻璃角色"),
      shot("tamsui-drama.jpg", "淡江·淡水虛擬劇本世界：第一集宮燈下的迎新與五個關卡"),
    ],
    sourceReferences: [
      {
        label: "公開站 · tku-tamsui-drama-world-k4x9.zeabur.app",
        href: "https://tku-tamsui-drama-world-k4x9.zeabur.app",
        note: "Zeabur 服務 tku-tamsui-drama-world。本次探測 RUNNING。不是 lunar-falcon-8p2r（那是 FrameLab）。",
      },
      {
        label: "GitHub · tku-tamsui-drama-world",
        href: "https://github.com/aa0968111723-prog/tku-tamsui-drama-world",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "skatehub",
    title: "直排輪基地 SkateHub",
    subtitle: "走向健康，走向陽光",
    category: "Interaction",
    year: "2026",
    status: "prototype",
    featured: false,
    summary: "直排輪款式與配件圖鑑，管理裝備、記錄滑行里程。公開站是 dd-k3f9，不是 Folio。",
    problem: "裝備散落在聊天室與雲端相簿。需要一個能看款式、記里程的小站。",
    role: "互動產品：圖鑑、裝備與里程紀錄。",
    decisions: [
      "公開站標題寫「走向健康，走向陽光」。",
      "網域是 dd-k3f9，不要跟 canva2（Folio）混用。",
    ],
    modalities: ["圖像", "互動"],
    process: ["打開 dd-k3f9.zeabur.app", "逛裝備圖鑑", "記錄滑行里程", "回來看自己的基地"],
    outputs: ["直排輪基地公開站"],
    stack: ["Web", "Zeabur"],
    limitations: ["個人紀錄依部署資料庫，不在此公開他人資料。"],
    links: {
      github: "https://github.com/aa0968111723-prog/dd",
      live: "https://dd-k3f9.zeabur.app",
    },
    media: [
      cover("skatehub.jpg", "直排輪基地光域靜物：白色直排輪與晨光水瓶"),
      shot("skatehub.jpg", "直排輪基地 SkateHub：走向健康走向陽光、裝備圖鑑與里程"),
    ],
    sourceReferences: [
      {
        label: "公開站 · dd-k3f9.zeabur.app",
        href: "https://dd-k3f9.zeabur.app",
        note: "Zeabur 服務 dd。本次探測 RUNNING。不是 Folio。",
      },
      {
        label: "GitHub · dd",
        href: "https://github.com/aa0968111723-prog/dd",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "zen-studio",
    title: "禪學社 Studio",
    subtitle: "社團現場的明亮工作台",
    category: "Creative Tool",
    year: "2026",
    status: "in-progress",
    featured: false,
    summary: "給淡江禪學社用的工作室殼：文宣、場次與日常作業放在同一盞燈下，而不是再開一個雲端硬碟資料夾。",
    problem: "社團文宣、場次與靈感散落。需要一個「今天可以創作什麼」的工作台。",
    role: "社團工具設計：日曆、活動、生成入口與素材庫。",
    decisions: [
      "首頁先問今天可以創作什麼，而不是先給後台選單。",
      "公開站是 delta-horizon-k7f2，GitHub 是 delta-horizon-cliff-fern。",
    ],
    modalities: ["圖像", "文宣", "日曆"],
    process: [
      "打開 delta-horizon-k7f2.zeabur.app",
      "看今日靈感與近期活動",
      "從「生成 IG 貼文／Carousel／Story」開始",
      "進畫布或月曆改一則到期內容",
    ],
    outputs: ["禪學社 Studio 公開站"],
    stack: ["Web", "Zeabur"],
    limitations: ["連 IG 官方發布需額外授權，未接上時只在工作室內排程。"],
    links: {
      github: "https://github.com/aa0968111723-prog/delta-horizon-cliff-fern",
      live: "https://delta-horizon-k7f2.zeabur.app",
    },
    media: [cover("zen-studio.jpg", "禪學社 Studio 光域靜物：茶碗、紙條與晨光窗")],
    sourceReferences: [
      {
        label: "公開站 · delta-horizon-k7f2.zeabur.app",
        href: "https://delta-horizon-k7f2.zeabur.app",
        note: "Zeabur 服務 delta-horizon-cliff-fern。本次探測 RUNNING。",
      },
      {
        label: "GitHub · delta-horizon-cliff-fern",
        href: "https://github.com/aa0968111723-prog/delta-horizon-cliff-fern",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "focus-challenge",
    title: "專注力挑戰賽",
    subtitle: "淡江禪學社現場 60 秒",
    category: "Real-world Experience",
    year: "2026",
    status: "in-progress",
    featured: false,
    summary: "社博／活動現場的 60 秒專注力挑戰：暖身、正式挑戰、即時看活動狀態。這是現場遊戲，不是心理測驗。",
    problem: "攤位需要立刻能玩、立刻能看到狀態的遊戲，而不是再填一張表。",
    role: "現場體驗設計：暖身、計時、成績與表單同步。",
    decisions: [
      "公開站標題寫「淡江大學禪學社｜專注力挑戰賽」。",
      "GitHub 是 ty；Zeabur 服務 leader-dna-sheet-sync。",
    ],
    modalities: ["互動", "現場"],
    process: [
      "打開 leader-dna-mcp-a7k2.zeabur.app",
      "先暖身再進入 60 秒正式挑戰",
      "看自己的結果",
      "主辦方可看活動狀態（需權限）",
    ],
    outputs: ["現場挑戰公開站"],
    stack: ["Web", "Google Sheets", "Zeabur"],
    limitations: ["成績寫入試算表，本作品集不展示個資或完整名冊。"],
    links: {
      github: "https://github.com/aa0968111723-prog/ty",
      live: "https://leader-dna-mcp-a7k2.zeabur.app",
    },
    media: [cover("focus-challenge.jpg", "專注力挑戰光域靜物：計時器與攤位平板")],
    sourceReferences: [
      {
        label: "公開站 · leader-dna-mcp-a7k2.zeabur.app",
        href: "https://leader-dna-mcp-a7k2.zeabur.app",
        note: "Zeabur 服務 leader-dna-sheet-sync。本次探測 RUNNING。",
      },
      {
        label: "GitHub · ty",
        href: "https://github.com/aa0968111723-prog/ty",
        note: "公開儲存庫。PRODUCT_CONTRACT.md 寫現場 60 秒挑戰。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "lumen",
    title: "Lumen",
    subtitle: "口袋裡的多模態語音創作球",
    category: "AI Product",
    year: "2026",
    status: "prototype",
    featured: false,
    summary: "說話就能設計、搜尋、生成，手指直接整理。公開站是 ai-chat-8rq3，GitHub 是 wood-ivory-blaze-maple。",
    problem: "創作入口太散。需要一個按住說話就能開始的球。",
    role: "語音介面與多模態入口設計。",
    decisions: [
      "首頁只有「想做什麼？」與按住說話，不做控制台。",
      "公開站 ai-chat-8rq3；GitHub wood-ivory-blaze-maple。",
    ],
    modalities: ["語音", "圖像", "影片"],
    process: [
      "打開 ai-chat-8rq3.zeabur.app",
      "點一下開始聽，或按住說話",
      "選做海報／拍照／開始做影片／長任務",
      "從最近專案繼續",
    ],
    outputs: ["Lumen 公開站"],
    stack: ["TanStack Start", "Postgres", "Zeabur"],
    limitations: ["雲端模型依金鑰；沒有金鑰時應誠實降級，不假裝已生成。"],
    links: {
      github: "https://github.com/aa0968111723-prog/wood-ivory-blaze-maple",
      live: "https://ai-chat-8rq3.zeabur.app",
    },
    media: [cover("lumen.jpg", "Lumen 光域靜物：玻璃桌上的語音光球")],
    sourceReferences: [
      {
        label: "公開站 · ai-chat-8rq3.zeabur.app",
        href: "https://ai-chat-8rq3.zeabur.app",
        note: "Zeabur 服務 wood-ivory-blaze-maple。本次探測 RUNNING。",
      },
      {
        label: "GitHub · wood-ivory-blaze-maple",
        href: "https://github.com/aa0968111723-prog/wood-ivory-blaze-maple",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "xiaocai",
    title: "小財記帳",
    subtitle: "個人收支的明亮小帳本",
    category: "Interaction",
    year: "2026",
    status: "prototype",
    featured: false,
    summary: "記一筆、看分類、知道這個月花到哪。公開站 untitled-5.zeabur.app。不是作品集後台。",
    problem: "個人收支不需要完整會計系統，需要一個開得起的小帳本。",
    role: "個人工具：記帳、分類、月覽。",
    decisions: ["公開站 untitled-5；GitHub 倉庫名是 -1。"],
    modalities: ["互動", "數字"],
    process: ["打開 untitled-5.zeabur.app", "記一筆收支", "看分類", "看這個月"],
    outputs: ["小財記帳公開站"],
    stack: ["Web", "Zeabur"],
    limitations: ["本次探測曾出現 502。連結保留，狀態會隨部署變動。"],
    links: {
      github: "https://github.com/aa0968111723-prog/-1",
      live: "https://untitled-5.zeabur.app",
    },
    media: [cover("xiaocai.jpg", "小財記帳光域靜物：玻璃帳本與硬幣")],
    sourceReferences: [
      {
        label: "公開站 · untitled-5.zeabur.app",
        href: "https://untitled-5.zeabur.app",
        note: "Zeabur 服務 untitled-5。本次探測可能 502，仍保留連結。",
      },
      {
        label: "GitHub · -1",
        href: "https://github.com/aa0968111723-prog/-1",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "tku-zen-agent",
    title: "禪學社工作台",
    subtitle: "淡江大學領袖禪學社 · Ask 模式",
    category: "Real-world Experience",
    year: "2026",
    status: "in-progress",
    featured: false,
    summary:
      "社團文書與現場問答的工作台。公開站 tku-zen-agent-k7f2，預設可帶 ?mode=ask。與本站展示的本地 tku-zen-ai 不是同一個產品。",
    problem: "社團文書、問答與現場需要一個代理工作台，不能跟本地禪意陪伴混成同一個產品。",
    role: "社團代理介面：Ask 模式與文書入口。",
    decisions: [
      "公開操作建議帶 ?mode=ask。",
      "與 tku-zen-ai（本地引擎）分開寫，避免假裝已接上雲端模型。",
    ],
    modalities: ["對話", "文書"],
    process: [
      "打開 tku-zen-agent-k7f2.zeabur.app/?mode=ask",
      "用 Ask 模式問社團文書或現場問題",
      "不要把回覆當成已審核公告",
    ],
    outputs: ["禪學社工作台公開站"],
    stack: ["Web", "Zeabur"],
    limitations: ["本次探測曾出現 502。與本地 tku-zen-ai 不是同一個產品。"],
    links: {
      github: "https://github.com/aa0968111723-prog/tku-zen-agent",
      live: "https://tku-zen-agent-k7f2.zeabur.app/?mode=ask",
    },
    media: [cover("tku-zen-agent.jpg", "禪學社工作台光域靜物：玻璃控制台與蓮花")],
    sourceReferences: [
      {
        label: "公開站 · tku-zen-agent-k7f2.zeabur.app",
        href: "https://tku-zen-agent-k7f2.zeabur.app/?mode=ask",
        note: "Zeabur 服務 tku-zen-agent。建議 ?mode=ask。本次探測可能 502。",
      },
      {
        label: "GitHub · tku-zen-agent",
        href: "https://github.com/aa0968111723-prog/tku-zen-agent",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "cutos",
    title: "CUTOS",
    subtitle: "用對話剪影片",
    category: "Multimodal",
    year: "2026",
    status: "prototype",
    featured: false,
    summary: "Conversational Video Editor：用句子找精華、看時間軸、產出剪輯計畫。公開站 cutos.zeabur.app，與 AI Director 同專案叢集。",
    problem: "粗剪仍要自己拖時間軸。需要先用句子找出精華。",
    role: "剪輯入口設計：對話、時間軸、計畫。",
    decisions: ["與 AI Director OS 同 Zeabur 專案叢集，但產品頁分開。"],
    modalities: ["影片", "對話", "時間軸"],
    process: ["打開 cutos.zeabur.app", "用一句話描述要找的精華", "看時間軸候選", "產出剪輯計畫"],
    outputs: ["CUTOS 公開站"],
    stack: ["Web", "Postgres", "Zeabur"],
    limitations: ["本次 Zeabur 狀態 SUSPENDED／502。連結保留。"],
    links: {
      github: "https://github.com/aa0968111723-prog/CUTOS",
      live: "https://cutos.zeabur.app",
    },
    media: [cover("cutos.jpg", "CUTOS 光域靜物：漂浮的影片格與光之剪刀")],
    sourceReferences: [
      {
        label: "公開站 · cutos.zeabur.app",
        href: "https://cutos.zeabur.app",
        note: "Zeabur 服務 cutos。本次探測 SUSPENDED／502。",
      },
      {
        label: "GitHub · CUTOS",
        href: "https://github.com/aa0968111723-prog/CUTOS",
        note: "公開儲存庫。",
      },
    ],
    visibility: "public",
  },
  {
    slug: "hermes-agent",
    title: "Hermes Agent",
    subtitle: "代理執行層（需登入）",
    category: "AI Product",
    year: "2026",
    status: "in-progress",
    featured: false,
    summary:
      "Nous Research Hermes Agent 的部署：會話、工具與 API。公開網域 455.zeabur.app，另有 hermes-agent-api.zeabur.app。打開 /sessions 會進登入頁。",
    problem: "Console 是工作區；真正跑工具的是 Agent。兩者要分開講，避免把控制台當成大腦。",
    role: "AI 產品架構：執行層與控制台分層。",
    decisions: [
      "映像是 docker.io/nousresearch/hermes-agent，不是本作品集的原始碼。",
      "本頁不展示 API key、Dashboard 密碼或 GitHub PAT。",
      "未登入只看得到 Sign in，不假裝已經進入會話。",
    ],
    modalities: ["對話", "任務", "MCP 工具"],
    process: [
      "開啟 455.zeabur.app/sessions",
      "登入（擁有者）",
      "看 sessions",
      "讓 Console（344.zeabur.app）連 HERMES_API_URL",
    ],
    outputs: ["公開網域 455.zeabur.app 與 hermes-agent-api.zeabur.app"],
    stack: ["Hermes Agent", "Docker", "Zeabur"],
    limitations: ["需要登入。作品集訪客看不到會話內容。本次探測服務可能暫停。"],
    links: {
      live: "https://455.zeabur.app/sessions",
    },
    media: [
      cover("hermes-agent.jpg", "Hermes Agent 光域靜物：玻璃終端與鑰匙卡"),
      shot("hermes-agent.jpg", "Hermes Agent 公開站未登入：Sign in，AUTH REQUIRED"),
    ],
    sourceReferences: [
      {
        label: "公開站 · 455.zeabur.app",
        href: "https://455.zeabur.app/sessions",
        note: "Zeabur 服務 hermes-agent。未登入是 Sign in。本次探測可能 SUSPENDED。",
      },
      {
        label: "API 網域 · hermes-agent-api.zeabur.app",
        href: "https://hermes-agent-api.zeabur.app",
        note: "同一服務的第二個網域。給 Console 連線，不是給訪客瀏覽的作品頁。",
      },
    ],
    visibility: "public",
  },
];
